CREATE TABLE "Organizer" (
  "Event_Year" int,
  "Person_Email" varchar(32),
  "Roles" varchar(512) NOT NULL,
  PRIMARY KEY ("Event_Year", "Person_Email")
);

CREATE TABLE "Person" (
  "Email" varchar(32) PRIMARY KEY,
  "Type" varchar(32) NOT NULL,
  "FirstName" varchar(32) NOT NULL,
  "LastName" varchar(32) NOT NULL,
  "Phone" varchar(10),
  "Department_Code" varchar(8) NOT NULL
);

CREATE TABLE "Department" (
  "Code" varchar(8) PRIMARY KEY,
  "Name" varchar(64) NOT NULL,
  "AUHFullName" varchar(32) NOT NULL,
  "AUHEmail" varchar(32) NOT NULL,
  "College_Code" varchar(8) NOT NULL
);

CREATE TABLE "College" (
  "Code" varchar(8) PRIMARY KEY,
  "Name" varchar(64) NOT NULL,
  "DeanFullName" varchar(32) NOT NULL,
  "DeanEmail" varchar(32) NOT NULL,
  "DeanFirstName" varchar(32) NOT NULL
);

CREATE TABLE "Event" (
  "Year" int PRIMARY KEY,
  "Date" date NOT NULL
);

CREATE TABLE "Person_Workshop" (
  "Person_Email" varchar(32),
  "Workshop_ID" int,
  "Role" varchar(32) NOT NULL,
  PRIMARY KEY ("Person_Email", "Workshop_ID")
);

CREATE TABLE "Workshop" (
  "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "State" varchar(32) NOT NULL,
  "Title" varchar(64) NOT NULL,
  "Advertisement" varchar(512),
  "Description" varchar(1024),
  "Capacity" int,
  "ComputerNeeds" varchar(128),
  "RoomNeeds" varchar(128),
  "MaxRepeat" int,
  "ParentQuestions" varchar(1024),
  "OtherInformation" varchar(512),
  "Event_Year" int NOT NULL,
  "Room_Name" varchar(32)
);

CREATE TABLE "Room" (
  "Name" varchar(32) PRIMARY KEY,
  "Type" varchar(32) NOT NULL,
  "Capacity" int NOT NULL,
  "Notes" varchar(64)
);

CREATE TABLE "TimeSlot" (
  "Event_Year" int,
  "ID" int,
  "Name" varchar(32) NOT NULL,
  "BegTime" time NOT NULL,
  "EndTime" time NOT NULL,
  PRIMARY KEY ("Event_Year", "ID")
);

CREATE TABLE "Workshop_TimeSlot" (
  "Workshop_ID" int,
  "TimeSlot_Event_Year" int,
  "TimeSlot_ID" int,
  PRIMARY KEY ("Workshop_ID", "TimeSlot_Event_Year", "TimeSlot_ID")
);

CREATE TABLE "Room_Feature" (
  "Room_Name" varchar(32),
  "Feature_Name" varchar(32),
  PRIMARY KEY ("Room_Name", "Feature_Name")
);

CREATE TABLE "Feature" (
  "Name" varchar(32) PRIMARY KEY,
  "Description" varchar(32) NOT NULL
);
