DROP TABLE IF EXISTS "Person_Workshop";
DROP TABLE IF EXISTS "Workshop_TimeSlot";
DROP TABLE IF EXISTS "Workshop";
DROP TABLE IF EXISTS "TimeSlot";

DROP TABLE IF EXISTS "Organizer";
DROP TABLE IF EXISTS "Event";

DROP TABLE IF EXISTS "Person";
DROP TABLE IF EXISTS "Department";
DROP TABLE IF EXISTS "College";

DROP TABLE IF EXISTS "Room_Feature";
DROP TABLE IF EXISTS "Room";
DROP TABLE IF EXISTS "Feature";
