LOAD DATA LOCAL INFILE '../data/College.csv'
INTO TABLE `College`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../data/Department.csv'
INTO TABLE `Department`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../data/Room.csv'
INTO TABLE `Room`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../data/Feature.csv'
INTO TABLE `Feature`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../data/Room_Feature.csv'
INTO TABLE `Room_Feature`
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

INSERT INTO `Event` VALUES
  (2024, '2024-03-23');

INSERT INTO `TimeSlot` VALUES
  (2024, 1, 'Workshop Period 1', '09:50', '10:50'),
  (2024, 2, 'Workshop Period 2', '11:00', '12:00'),
  (2024, 3, 'Workshop Period 3', '13:35', '14:35');
